name: RealScoreboard
version: ${project.version}
main: josegamerpt.realscoreboard.RealScoreboardPlugin
api-version: 1.13
softdepend: [ Vault, PlaceholderAPI ]
authors: [ JoseGamer_PT ]
description: Lightweight and efficient scoreboard manager.
